name: Sync with upstream

on:
  # Runs at 10:00 UTC every day
  #schedule:
  #  - cron:  '0 10 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.LUNARCLIENT_SCOPED_TOKEN }}
      - name: Fetch release version
        run: |
          python3 -m venv .venv
          source .venv/bin/active
          pip3 install requests beautifulsoup4
          VERSION=$(python3 .github/workflows/get_latest.py)
          if [ ${#VERSION} -gt 0 ]; then
            sed -i 's/^\(version: \).*$/\1'"$VERSION"'/' snap/snapcraft.yaml
          fi
          
      - name: Check for modified files
        id: git-check
        run: |
          MODIFIED=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
          echo "modified=$MODIFIED" >> $GITHUB_OUTPUT
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Ken VanDine'
          git config --global user.email 'ken@vandine.org'
          git commit -am "Automatic sync to latest release"
          git push

